services:
  classfinder:
    build:
      context: .
    ports:
      - 7842:7842
    volumes:
      - ./data:/data
      - ./logs:/logs
    restart: always
    hostname: classfinder
    stop_signal: SIGINT
    environment:
      - DB_PATH=sqlite:////data/db.sqlite3
      - LOG_DIR=/logs